<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserSettings', 'doctrine');

/**
 * BaseUserSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property boolean $is_fillet_locked
 * @property boolean $is_fillet_lock_message_shown
 * @property sfGuardUser $User
 * 
 * @method integer      getUserId()                       Returns the current record's "user_id" value
 * @method boolean      getIsFilletLocked()               Returns the current record's "is_fillet_locked" value
 * @method boolean      getIsFilletLockMessageShown()     Returns the current record's "is_fillet_lock_message_shown" value
 * @method sfGuardUser  getUser()                         Returns the current record's "User" value
 * @method UserSettings setUserId()                       Sets the current record's "user_id" value
 * @method UserSettings setIsFilletLocked()               Sets the current record's "is_fillet_locked" value
 * @method UserSettings setIsFilletLockMessageShown()     Sets the current record's "is_fillet_lock_message_shown" value
 * @method UserSettings setUser()                         Sets the current record's "User" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_settings');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_fillet_locked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_fillet_lock_message_shown', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}