<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('News', 'doctrine');

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property string $title
 * @property string $brief
 * @property string $content
 * @property string $image
 * 
 * @method date   getDate()    Returns the current record's "date" value
 * @method string getTitle()   Returns the current record's "title" value
 * @method string getBrief()   Returns the current record's "brief" value
 * @method string getContent() Returns the current record's "content" value
 * @method string getImage()   Returns the current record's "image" value
 * @method News   setDate()    Sets the current record's "date" value
 * @method News   setTitle()   Sets the current record's "title" value
 * @method News   setBrief()   Sets the current record's "brief" value
 * @method News   setContent() Sets the current record's "content" value
 * @method News   setImage()   Sets the current record's "image" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('brief', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $imagebuilder0 = new Doctrine_Template_ImageBuilder(array(
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             'builder' => 'ProjectHelper::slug_builder',
             ));
        $meta0 = new Doctrine_Template_Meta(array(
             'title_field' => 'title',
             ));
        $this->actAs($imagebuilder0);
        $this->actAs($sluggable0);
        $this->actAs($meta0);
    }
}