<?php

/**
 * BaseThread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Microtasks
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getMicrotasks() Returns the current record's "Microtasks" collection
 * @method Thread              setName()       Sets the current record's "name" value
 * @method Thread              setMicrotasks() Sets the current record's "Microtasks" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseThread extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('thread');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Microtask as Microtasks', array(
             'local' => 'id',
             'foreign' => 'thread_id'));

        $user0 = new Doctrine_Template_User();
        $this->actAs($user0);
    }
}