<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BlogTag', 'doctrine');

/**
 * BaseBlogTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $BlogPosts
 * @property Doctrine_Collection $BlogPost2BlogTag
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method Doctrine_Collection getBlogPosts()        Returns the current record's "BlogPosts" collection
 * @method Doctrine_Collection getBlogPost2BlogTag() Returns the current record's "BlogPost2BlogTag" collection
 * @method BlogTag             setName()             Sets the current record's "name" value
 * @method BlogTag             setBlogPosts()        Sets the current record's "BlogPosts" collection
 * @method BlogTag             setBlogPost2BlogTag() Sets the current record's "BlogPost2BlogTag" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_tag');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BlogPost as BlogPosts', array(
             'refClass' => 'BlogPost2BlogTag',
             'local' => 'blog_tag_id',
             'foreign' => 'blog_post_id'));

        $this->hasMany('BlogPost2BlogTag', array(
             'local' => 'id',
             'foreign' => 'blog_tag_id'));
    }
}