<?php

/**
 * BaseBacklog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * 
 * @method string  getDescription() Returns the current record's "description" value
 * @method Backlog setDescription() Sets the current record's "description" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBacklog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('backlog');
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $user0 = new Doctrine_Template_User(array(
             ));
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($user0);
        $this->actAs($timestampable0);
    }
}