<?php

/**
 * BacklogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BacklogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BacklogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Backlog');
    }
}