<?php

/**
 * BlogPostCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPostComment');
    }
}