<?php

/**
 * MicrotaskPresetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MicrotaskPresetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MicrotaskPresetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MicrotaskPreset');
    }
	
	public static function getDashboardQuery($a = 'm') {
		return Q::c('MicrotaskPreset', $a)
						->where("$a.user_id = ?", sfContext::getInstance()->getUser()->getGuardUser()->getId())
						;
	}	
}