<?php

/**
 * MicrotaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MicrotaskTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object MicrotaskTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('Microtask');
	}

	public static function getDashboardQuery($a = 'm') {
		return Q::c('Microtask', $a)
						->where("$a.user_id = ?", sfContext::getInstance()->getUser()->getGuardUser()->getId())
						->addWhere("$a.status = ?", 'new')
						->orderBy("$a.is_blocker DESC, $a.priority DESC, $a.created_at");
	}
	
	public static function hasBlocker() {
		return self::getDashboardQuery('m')
				->addWhere('m.is_blocker = ?', true)
				->count()
				;
	}
	
	public static function isOpenTaskLimit() {
		return self::getDashboardQuery()->count() >= MyConfig::getInteger('open_task_limit');
	}

}