<?php

/**
 * MicrotaskPreset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MicrotaskPreset extends BaseMicrotaskPreset
{
	public function __toString() {
		$str = P::cut($this->getDescription());
		if($this->getType() != 'down'){
			$str .= "({$this->getType()})";
		}
		return $str;
	}
}