<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News extends BaseNews
{
    public $sUplDir = '';    

    
    public function getThumbnail()
    {
        return $this->getPhotoPath() . '.small';
    }

    public function getTiny()
    {
        return $this->getPhotoPath() . '.tiny';
    }    
    
    public function getMid()
    {
        return $this->getPhotoPath() . '.mid';
    }
    
}