<?php

/**
 * ThreadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThreadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThreadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Thread');
    }
}