# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets: []
#    - /bootstrap/css/bootstrap.css
#    - /bootstrap/css/bootstrap-responsive.css
#    - ui-lightness/jquery-ui-1.8.16.custom.css    
#    #- /bootstrap/css/bootstrap.icon-large.min.css
#    - library/imgareaselect-default.css
#    - library/imgareaselect-animated.css    
#    - admin_front.css
#    - style.css
#    - system.css
    

  javascripts: []
#    - http://maps.google.com/maps/api/js?sensor=false    
#    - library/jquery-1.7.1.min.js
#    - /bootstrap/js/bootstrap.min.js
#    - jquery-ui-1.8.16.custom.min.js    
#    - system.js
#    - jquery.cookie.js
#    - jquery.jcarousel.min.js
#    - jquery.dropotron-1.0.js
#    - http://maps.googleapis.com/maps/api/js?key=AIzaSyBVhUpviRpn-KGpop4SHyZ2SerETg0EiUg&sensor=false   
#    - sfForm.js
##    - jquery.slidertron-1.1.js
#    - jquery.thickbox.js
#    - library/jquery.imgareaselect.js      
#    - admin_front.js
#    - global.js

  has_layout:     true
  layout:         layout
