generator:
  class: myDoctrineGenerator
  param:
    model_class:           BlogPost
    theme:                 my_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          blog_post
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Blog Posts
        display: [name, date, brief, _image, is_published]
      filter:
        display: [name, date, is_published]
      form:    ~
      edit:    ~
      new:     ~
      
#    extra:
#      export:
#        filename: '%date% - My export'
#        mode: 'csv'      #[csv, xlsx]
#        dateformat: 'Y.m.d'
#        encoding: 'windows-1251'
#      javascript:
#        remoteoptions:
#          purchase:
#            trigger: purchase_id
#            url: util/purchasePriceByPurchase
#            update: purchase_price_id
#        remotedata:
#          customer:
#            trigger: customer_id
#            url: util/remoteCustomerData
#            fields: [customer_name, customer_address]  
#        showhide_form_fields:
#          selloff:
#            toggler: selloff_enabled
#            fields: [selloff_price, selloff_end_date]
