generator:
  class: myDoctrineGenerator
  param:
    model_class:           News
    theme:                 my_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
        display: [date, title, _image, brief]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
